### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by XavierGeerinck** [benallfree/enchant-puppeteer#1]
Just as an FYI, I was trying out your awesome plugin and got the following issue:

```
TypeError: Cannot read property 'bind' of undefined
    at E:\Projects\<MASKED>\npm-module-puppeteer\node_modules\enchant-puppeteer\dist\enchantHTTPRequest.js:100:22
     at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

Which resolves to the following piece of code

```javascript
return oldContinue
    .bind(this)(this.continueRequestOverrides)
    .then(() => {
        this._finalizeEmitter.emit(exports.RequestInterceptionOutcome.Continued);
        this._finalizeEmitter.emit(exports.RequestInterceptionOutcome.Finalized);
    })
```

Found at:

https://github.com/benallfree/enchant-puppeteer/blob/8764c31bf965c25c96e56d448f3abaf9981325c4/src/enchantHTTPRequest.ts#L136

**Comment by benallfree** [comment]
What version of pptr are you using?

**Comment by XavierGeerinck** [comment]
5.5.0

**Comment by benallfree** [comment]
Could you do me a favor and see if you get the same error when you do:

```bash
git clone git@github.com:benallfree/enchant-puppeteer.git
cd enchant-puppeteer
yarn test:5x
```

**Comment by XavierGeerinck** [comment]
Definitely, when I run this I get the following:

```
 E:\Projects\enchant-puppeteer\dist\enchantHTTPRequest.js:30
        obj._finalizeEmitter = new _EventEmitter();
                               ^
TypeError: _EventEmitter is not a constructor
    at new klass (E:\Projects\enchant-puppeteer\dist\enchantHTTPRequest.js:30:32)
    at NetworkManager._onRequest (E:\Projects\enchant-puppeteer\test\5.x\node_modules\puppeteer\lib\cjs\puppeteer\common\NetworkManager.js:208:25)
    at NetworkManager.klass._onRequest (E:\Projects\enchant-puppeteer\dist\enchantNetworkManager.js:11:32)
    at NetworkManager._onRequestPaused (E:\Projects\enchant-puppeteer\test\5.x\node_modules\puppeteer\lib\cjs\puppeteer\common\NetworkManager.js:187:18)
    at E:\Projects\enchant-puppeteer\test\5.x\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (E:\Projects\enchant-puppeteer\test\5.x\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at CDPSession.emit (E:\Projects\enchant-puppeteer\test\5.x\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at CDPSession._onMessage (E:\Projects\enchant-puppeteer\test\5.x\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:225:18)
    at Connection._onMessage (E:\Projects\enchant-puppeteer\test\5.x\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:101:25)
error Command failed with exit code 1.
```

**Comment by XavierGeerinck** [comment]
Note: the bug apparently appears when creating a browser + page for the second time.

I.e. I have a long running script that spins up a browser and page, then executes and then deletes this all. When this script runs for a second time, it breaks the `.bind` code

**Comment by benallfree** [comment]
@XavierGeerinck Thanks for helping me! Sorry about the _EventEmitter bug, it's fixed in master. 

> deletes this all

Can you please paste your script for a little more context? I'm not following what you mean. `enchantPuppeteer()` should monkey-patch the module. Unless that module gets reloaded by nodejs, it should stay patched regardless of anything you do with Puppeteer.

**Comment by XavierGeerinck** [comment]
Thank you for the quick fix! 

What I do is something like this:

```javascript
class Browser {
    async initialize() {
        // Create Browser
        const b = await puppeteer.launch();
        enchantPuppeteer();
    }
}

for (let i = 0; i < 5; i++) {
    let b = new Browser();
    await b.initialize();
}
```

I will try to recreate it in this kind of code fashion meanwhile

**Comment by XavierGeerinck** [comment]
This will recreate the issue that I am having, it seems to be due to the setRequestInterception(true)

```javascript
const puppeteer = require('puppeteer');
const { enchantPuppeteer } = require("enchant-puppeteer");

class Browser {
  initialize() {
    return new Promise(async (resolve, reject) => {
      const b = await puppeteer.launch({ devtools: false, headless: true });
      enchantPuppeteer();

      const p = await b.newPage();

      await p.setRequestInterception(true) // without this it works!
      await p.goto('https://google.com');
      await b.close();

      return resolve();
    })
  }
}

async function start() {
  for (let i = 0; i < 3; i++) {
    console.log(`Initializing ${i}`)
    let b = new Browser();
    await b.initialize();
  }

  console.log('done')
}

start().catch(e => console.error(e));
```

**Comment by XavierGeerinck** [comment]
p.s. while utilizing 0.03 I get following error as well now:

```
throw new Error(`Could not enchant any version of ${moduleName} on ${rootPath}. Only Puppeteer 3.x or above is supported, or your module path is wrong.`);
```

**Comment by benallfree** [comment]
@XavierGeerinck fixed in 0.0.4 and master 👍

**Comment by XavierGeerinck** [comment]
Just for my own information, I guess due to the way modules work in node, it most likely tried to repatch each time but since it was already patched it crashed?

**Comment by XavierGeerinck** [comment]
(it works now here btw! could you remove the loggings as well?)

**Comment by XavierGeerinck** [comment]
P.S. there is still a bug in the findModule, it tries to find but since I am using a local package reference it is going to the wrong path.

I.e. I have package1/ and package2/ package1 is the main one that utilizes package2 but package2 uses the enchant-puppeteer, but then it tries to find puppeteer in package1 while it's actually in package2

**Comment by benallfree** [comment]
@XavierGeerinck Yes that is exactly what was causing it, but I think it was a good fix/check to add :)

> could you remove the loggings as well

 `enchantPuppeteer({logLevel: 'none'})` - do you think that should be the default?

> it is going to the wrong path

See Advanced Usage in the readme. `enchantPuppeteer({ modulePath: '/path/to/module/puppeteer'})`

Thank you for all your help!!

**Comment by XavierGeerinck** [comment]
Thanks a lot! I indeed think `logLevel: none` should be the default.

**Comment by benallfree** [comment]
All fixed in 0.0.5 and `master`!

Let me know if you hit any other issues, I think it's really cool that you're helping test this.

**Comment by XavierGeerinck** [comment]
Awesome! Just pulled it and it's working at my end! Thanks a lot for the fast work and beautiful fixes! I really hope that Puppeteer sees the light and implements this upstream as well :)

**Comment by benallfree** [comment]
Me too! But, it's been like this since v1 so I'm not sure they share our philosophy.

Closing this issue, please feel welcome to continue offering feedback and reports!
